### PR TITLE
Update to React 16.3 (context)

### LINKED ISSUE #3: Context API
Obviously React is getting a new Context API, but you have to support more than 16.3 with Formik so you won't be able to use it. I [asked Dan Abramov on Twitter](https://twitter.com/dan_abramov/status/979079793110069249) and he recommended using [React Broadcast](https://github.com/ReactTraining/react-broadcast) to polyfill it for older versions. What about adding this to `formik-effect`/`formik` instead of using the old context api? The primary reason is this:

```js
const MyPureComponent extends React.PureComponent {
  render() {
    return this.props.children;
  }
}

const MyForm = (props) => (
  <Formik
      onSubmit={values => console.log(values)}
      initialValues={{ firstName: '', lastName: '', email: '' }}
      render={props =>
        <Form className="whatever">
          <MyPureCompoent>
            <Effect onChange={(currentFormikState, nextFormikState) => {
                 // This will never receive changes as PureComponent props never change
                 // and wont pass them down to their children
              }} 
            />
          </MyPureComponent>
          <Field name="firstName" placeholder="First Name" />
          <Field name="lastName" placeholder="Last Name" />
          <Field name="email" type="email" placeholder="Email Address" />
          <button type="submit">Submit</button>
         
        </Form>}
    />
);
```

### PR DESCRIPTION
**Pull request by JulienMalige**
Hi @jaredpalmer,

I'm trying to update formik-effect to use it with the new Context API (fix #3 #4 #6).
The code looks ok for me, but the Formik prop of the Effect consumer is always empty.

Is my code not correct ?

### CODE REVIEW

**Comment by JulienMalige** [comment]
Using this code in our projet (as component, not as library) it works.
So the issue must be **related to the dependencies**.

**Review by jaredpalmer — APPROVED** [review]

**Comment by danielkcz** [comment]
Sooo, why this hasn't been merged yet? :)

**Comment by danielkcz** [comment]
@JulienMalige Oh, the test is failing because it's trying to run `test` script, but no such is defined. Can you perhaps add it?

**Comment by imamatory** [comment]
Any updates?

**Comment by danielkcz** [comment]
@imamatory Given that Formik is [getting rewritten to Hooks](https://github.com/jaredpalmer/formik/issues/828), I don't think this PR is relevant anymore. Or at least that functionality of this package will be included in core Formik.

**Pull request closed without merging**
